name: mqtt_subscriber
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fimber: 0.6.1
  flutter_local_notifications: 5.0.0+4
  sqflite: 2.0.0+3
  mqtt_client: 9.3.1
  path_provider: 2.0.1
  intl: 0.17.0
  uuid: 3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
